### ISSUE TITLE
escaped _ should be parsed a space

### ISSUE THREAD

**Issue by nico202** [BioJulia/YAML.jl#40]
this is what yamlint seems to be doing, at least.
we should add 
> , "_" => ' '

https://github.com/dcjones/YAML.jl/blob/b469dad382d7be00bd41f75e85bb08029fcfcbac/src/scanner.jl#L1206

**Comment by sglyon** [comment]
From what I can see on the spec ([here](http://www.yaml.org/spec/current.html#id2517668)) an escaped `_` should be treated as a non-breaking space (spelled `'\u00A0'` in Julia

**Comment by nico202** [comment]
Fine! I could not find the specs, thanks! Can it be added? Along with any other Missoni

**Comment by nico202** [comment]
*missing. Can't edit the message on github mobile

**Comment by sglyon** [comment]
Yes, definitely. The closer we are to the spec the better.

I don't personally have the time to add them. Would you be willing to take a stab at putting together a PR that goes through the list in the spec and adds any missing entries?

**Comment by nico202** [comment]
Yes! I'll PR when I'll be back home

**Comment by nico202** [comment]
It's the only one missing. I placed it in the same position in the list, between N (next-line) and L (line-separator)

**Comment by kescobo** [comment]
Looks like #2
