### ISSUE TITLE
Package should belong to JuliaIO

### ISSUE THREAD

**Issue by o314** [BioJulia/YAML.jl#62]
Hello BioJulia,

I'm fighting with entropy in the Julia world those days. It's becoming very,
very hard to know where to grasp a recommended / authoritative package among
Julia ones, even in 2019.

Doesn't this package would be better hosted at
[JuliaIO](http://github.com/JuliaIO) so anyone concerned would
find it easily ?

Thanks

**Comment by jgreener64** [comment]
I can't comment on this package individually as I haven't been involved with it, but in my view orgs arise organically around groups of like-minded developers. It kind of makes sense that packages stay close to the orgs involved in writing and maintaining them.

Which org a package is in shouldn't matter provided there are separate systems for searching and recommending packages. I admit that this is lacking at the minute in the general ecosystem though. However a Google search for "YAML julia" or "YAML jl" both return this repository first.

**Comment by kescobo** [comment]
The question is whether we expect people will look directly for a solution to parsing YAML files (so @jgreener64 's google search info is useful), or whether we'd expect people to browse through JuliaIO to see what file types are supported. The former is much closer to the way I'd expect to search, but it's not unreasonable to think there are some in the latter camp. 

That said, I also agree that package search is a known and open issue. Until that gets ironed out, it might make sense to move it, but would also require buy-in from JuliaIO, and the willingness of both maintainers and JuliaIO folks to make the move.

**Comment by BenJWard** [comment]
Heya @o314, YAML.jl is in BioJulia I think because the origional author was a heavy developer of a lot of BioJulia's early code, and as he scaled down his activity YAML maintanance, which used to exist on their profile suffered a bit, so I said something to the tune of "Hey as a stopgap, BioJulia can house it until it gets a proper owner". If JuliaIO would be happy to take on YAML.jl then I would be very happy with that.

**Comment by o314** [comment]
Hello BioJulia people.

Thanks your for constructive replies,
and all the work behind it !

**Comment by BenJWard** [comment]
I'm going to close this issue unless the topic arises again, by someone raising the possibility of adopting YAML.jl
