### ISSUE TITLE
New release so that write_file is available?

### ISSUE THREAD

**Issue by JockLawrie** [BioJulia/YAML.jl#73]
Hi there,

I have a need to write simple data structures to YAML and the new `write_file` function is sufficient.
Would it be possible to release a new version of this package so that `write_file` is available in the release?
(currently I have to `] add YAML#master`, I'd prefer to just `] add YAML`)

Cheers,
Jock

**Comment by GunnarFarneback** [comment]
This package had its last release 15 months ago and has since received two major features (#48, #68) and a significant performance improvement (#64). Is there anything that can be done to help the maintainers get a new release made?

**Comment by junglegobs** [comment]
If I understand correctly, the `write_file` function has been written (if possibly not completed), but isn't available? I understand it could take time to get this to work reliably, however the documentation is currently a bit misleading since it makes it seem like this function is available.

**Comment by kescobo** [comment]
Looks good to me. @BenJWard We should probably enable the register bot for the general registry for this one, I don't think it makes sense for people to use the biojulia registry for such general functionality

**Comment by GunnarFarneback** [comment]
Yes, YAML needs to be in the General registry. If nothing else there are packages in General that depend on YAML.

**Comment by kescobo** [comment]
>If nothing else there are packages in General that depend on YAML.

I mean, in principle they can continue to depend on the older version of it. But I think we'd like to move this package out of BioJulia anyway. It doesn't make sense to block new versions from coming out until that happens. Unfortunately, I don't have admin rights for this repo, so I can't enable it.

**Comment by ChrisRackauckas** [comment]
Weave can't use Compat v3 because of this. 15 months without a release is a pretty long lasting issue. If BioJulia only wants to maintain their own registry, that's fine, but then we should at least fork the repo so that Weave isn't blocked.

**Comment by kescobo** [comment]
No need to fork, if there are other people that want to maintain it, we're happy for it to move to another org (see eg #62). That said, I'm also happy to take on stewardship of the repo (not necessarily development, but review of PRs and making releases to General etc) if that's needed. But I only have write access at the moment, and I need admin to enable the release bot for General.

Paging @BenJWard and @bicycle1885

**Comment by kescobo** [comment]
I suppose I could change the Project.toml and make a github release if someone could manually make a PR to General...

**Comment by GunnarFarneback** [comment]
You can register with the Registrator web interface without admin repository privileges. See https://juliaregistries.github.io/Registrator.jl/stable/webui/#Usage-(For-Package-Maintainers)-1.

**Comment by kescobo** [comment]
OK, I can do that. Should be a minor release right? AFAICT there are no breaking changes...

**Comment by GunnarFarneback** [comment]
> AFAICT there are no breaking changes...

Not quite. See https://github.com/BioJulia/YAML.jl/pull/64#issuecomment-457911842.

**Comment by GunnarFarneback** [comment]
> Can anyone tell what version of Codecs I should use as a lower bound?

Looks to me like Codecs is used exactly once, to decode Base64. The very first commit to Codecs is titled "Initial work. Base64 encoder.", so I would suspect every released version can do that.

**Comment by GunnarFarneback** [comment]
A more important matter is that Registrator won't accept compatibility with Julia versions earlier than 0.7, so I would suggest dropping pre-1.0 support entirely for the new version. Then the only version of Codecs that is compatible with 1.0 is 0.5.

Compat is more tricky. It probably should just be cleaned out. Let me have a look.

**Comment by BenJWard** [comment]
Registrator.jl has been enabled for YAML.jl

**Comment by ChrisRackauckas** [comment]
Thanks!

**Comment by BenJWard** [comment]
@kescobo You've also been given admin level for YAML.jl

**Comment by kescobo** [comment]
Fantastic, thanks! @GunnarFarneback has a PR to get us up to snuff: #76 
Gonna merge and register that end of day

**Comment by kescobo** [comment]
Closed by #76
